app/mod_torrent/controllers.py
from flask import Blueprint, render_template, jsonify, request
import re
import app

mod_torrent = Blueprint('torrent', __name__, url_prefix='/torrent')

@mod_torrent.route('/all')
def all():
	results = []

	torrents = app.mod_torrent.torrents

	for key in torrents:
		torrent = torrents[key]
		handler = torrent.get('handler',None)
		future = torrent.get('future',None)

		if handler and future:
			name = handler.name()
			status = handler.status()

			if handler.is_paused():
				state = 0
			else:
				state = status.state

			results.append({
				'uid': key,
				'info_hash': str(handler.info_hash()),
				'name': name,
				'download_rate': status.download_rate,
				'upload_rate': status.upload_rate,
				'peers': status.num_peers,
				'state': state,
				'total_wanted_done': status.total_wanted_done,
				'total_wanted': status.total_wanted
			})

	return jsonify(results)

@mod_torrent.route('/add', methods=['POST'])
def add():
	data = request.get_json()
	url = data.get('url',None)

	uid = None
	success = False

	torrents = app.mod_torrent.torrents

	if url:
		if url.startswith('magnet:?'):
			hashes = []

			pattern = re.compile(r'xt(?:\\.\d+)?=urn:(?:[a-z0-9]+)?:([A-Z0-9]+)',re.IGNORECASE)
			for match in pattern.finditer(url):
				hashes.append(match.group(1))

			if hashes:
				found = False

				for key in torrents:
					handler = torrents[key]['handler']
					info_hash = str(handler.info_hash())

					for h in hashes:
						if h == info_hash:
							found = True
							break

					if found:
						break

				if not found:
					success = True

					app.mod_torrent.add_torrent(url)

	results = {
		'uid': uid,
		'success': success
	}

	return jsonify(results)

@mod_torrent.route('/delete', methods=['POST'])
def delete():
	data = request.get_json()
	uid = data.get('uid',None)

	if uid:
		success = app.mod_torrent.delete_torrent(uid) != None
	else:
		success = False

	results = {
		'uid': uid,
		'success': success
	}

	return jsonify(results)

app/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
	{% include '_header.html' %}

	<body>
		{% include '_navbar.html' %}

		<div class="container-fluid">
			<br/>

			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<div class="card-header"><i class="fas fa-cloud-download-alt"></i> Torrents</div>
						<div class="card-body">
							<div id="torrents_table_toolbar">
								<button type="button" class="btn btn-outline-secondary" id="add_torrent_btn">Add Torrent</button>
							</div>

							<div class="table-responsive">
								<table class="table table-bordered table-hover" id="torrents_table"></table>
							</div>
						</div>
					</div>
				</div>
			</div>

			<br/>
		</div>

		<div class="modal fade" id="add_torrent_modal">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title">Add Torrent</h4>
						<button type="button" class="close" data-dismiss="modal">&times;</button>
					</div>

					<div class="modal-body">
						<div class="col-md-12">
							<input type="text" class="form-control" id="url" autocomplete="off" placeholder="Enter a magnet link">
						</div>
					</div>

					<div class="modal-footer">
						<div class="container text-center">
							<button type="button" class="btn btn-outline-primary" id="submit">Add</button>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="modal fade" id="delete_torrent_modal">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title">Delete Torrent</h4>
						<button type="button" class="close" data-dismiss="modal">&times;</button>
					</div>

					<div class="modal-body">
						<div class="col-md-12">
							<p>Are you sure you want to delete "<span id="name"></span>"? (UID=<span id="uid"></span>)</p>
						</div>
					</div>

					<div class="modal-footer">
						<button type="button" class="btn btn-outline-danger" id="submit">Yes</button>
						<button type="button" class="btn btn-outline-secondary" data-dismiss="modal">No</button>
					</div>
				</div>
			</div>
		</div>

		{% include '_scripts.html' %}

		{% raw %}
		<script id="progress-bar-template" type="text/x-handlebars-template">
			<div class="progress" style="height:8px">
				<div class="progress-bar progress-bar-striped progress-bar-animated {{class}}" style="width:{{progress}}%;height:8px"></div>
			</div>
			<div class="text-right"><small>{{message}}</small></div>
		</script>
		{% endraw %}

		{% raw %}
		<script id="delete-button-template" type="text/x-handlebars-template">
			<button type="button" class="btn btn-link" onclick="deleteTorrent('{{name}}','{{uid}}')"><i class="far fa-trash-alt color-red"></i></button>
		</script>
		{% endraw %}

		<script>
			var $torrents_table;
			var $add_torrent_btn;
			var $add_torrent_modal;
			var $add_torrent_modal_url;
			var $add_torrent_modal_submit;
			var $delete_torrent_modal;
			var $delete_torrent_name;
			var $delete_torrent_uid;
			var $delete_torrent_submit;

			var progress_bar_template = Handlebars.compile(document.getElementById('progress-bar-template').innerHTML);
			var delete_button_template = Handlebars.compile(document.getElementById('delete-button-template').innerHTML);

			function deleteTorrent(name,uid) {
				$delete_torrent_modal.attr('data-name',name);
				$delete_torrent_modal.attr('data-uid',uid);

				$delete_torrent_modal.modal('show');
			}

			function resetTorrentsTableTimeout() {
				var timeout = $torrents_table.attr('timeout');

				if (timeout) {
					clearTimeout(timeout);
				}
			}

			function refreshTorrentsTable(silent) {
				resetTorrentsTableTimeout();

				if (silent === undefined) {
					silent = true;
				}

				$torrents_table.removeAttr('timeout');
				$torrents_table.bootstrapTable('refresh',{silent: silent});
			}

			function getProgressBarInfo(state) {
				var cls;
				var progress;
				var message;

				switch (state) {
					case 1: {
						cls = 'bg-info';
						message = 'Checking';
						progress = -5;
						break;
					}

					case 2: {
						cls = 'bg-info';
						message = 'Downloading metadata';
						progress = -1;
						break;
					}

					case 3: {
						cls = '';
						progress = null;
						message = 'Downloading';
						break;
					}

					case 4: {
						cls = 'bg-success';
						message = 'Finished';
						progress = 101;
						break;
					}

					case 5: {
						cls = 'bg-success';
						message = 'Seeding';
						progress = 102;
						break;
					}

					case 6: {
						cls = 'bg-info';
						message = 'Allocating';
						progress = -2;
						break;
					}

					case 7: {
						cls = 'bg-info';
						message = 'Checking fastresume';
						progress = -4;
						break;
					}					

					default: {
						cls = 'bg-info';
						message = 'Queued';
						progress = -6;
						break;
					}
				}

				var info = {
					'class': cls,
					'message': message,
					'progress': progress
				};

				return info;
			}

			$(document).ready(function() {
				$torrents_table = $('#torrents_table');
				$add_torrent_btn = $('#add_torrent_btn');
				$add_torrent_modal = $('#add_torrent_modal');
				$add_torrent_modal_url = $add_torrent_modal.find('#url');
				$add_torrent_modal_submit = $add_torrent_modal.find('#submit');
				$delete_torrent_modal = $('#delete_torrent_modal');
				$delete_torrent_name = $delete_torrent_modal.find('#name');
				$delete_torrent_uid = $delete_torrent_modal.find('#uid');
				$delete_torrent_submit = $delete_torrent_modal.find('#submit');

				$torrents_table.bootstrapTable({
					url: '{{ url_for("torrent.all") }}',
					showRefresh: true,
					search: true,
					pagination: true,
					buttonsClass: 'outline-secondary',
					icons: {
						refresh: 'fas fa-sync'
					},
					toolbar: '#torrents_table_toolbar',
					responseHandler: function(res) {
						var arr = [];
						
						for (var i = 0; i < res.length; i++) {
							var r = res[i];
							
							var uid = r['uid'];
							var name = r['name'];
							var download_rate = r['download_rate'];
							var upload_rate = r['upload_rate'];
							var state = r['state'];
							var total_wanted_done = r['total_wanted_done'];
							var total_wanted = r['total_wanted'];

							var info = getProgressBarInfo(state);
							var cls = info['class'];
							var progress = info['progress'];
							var message = info['message'];

							if (progress == null) {
								progress = Math.round((total_wanted_done / total_wanted) * 100);
								message = message + ' - ' + progress + '%';
							}

							var width;
							if (state == 3) {
								width = progress;
							} else {
								width = 100;
							}

							var progress_col = progress_bar_template({
									'class': cls,
									'message': message,
									'progress': width
								});

							var download_rate_col = formatBytes(download_rate,1);

							var upload_rate_col = formatBytes(upload_rate,1);

							
							var delete_col = delete_button_template({
								'name': name,
								'uid': uid
							});

							d = {
								'1': (i + 1),
								'2': name,
								'3': progress_col,
								'4': download_rate_col,
								'5': upload_rate_col,
								'6': delete_col,
								'progress': progress,
								'download_rate': download_rate,
								'upload_rate': upload_rate
							}
							
							arr.push(d);
						}
						
						return arr;
					},
					columns: [{
						field: '1',
						title: '#',
						sortable: 'true',
						align: 'center'
					}, {
						field: '2',
						title: 'Name',
						sortable: 'true',
						width: '60%'
					}, {
						field: '3',
						title: 'Progress',
						sortable: 'true',
						width: '40%',
						sortName: 'progress'
					}, {
						field: '4',
						title: 'Download Rate',
						sortable: 'true',
						sortName: 'download_rate'
					}, {
						field: '5',
						title: 'Upload Rate',
						sortable: 'true',
						sortName: 'upload_rate'
					}, {
						field: '6',
						title: '<i class="far fa-trash-alt"></i>',
						align: 'center'
					}],
					onRefresh: function(params) {
						resetTorrentsTableTimeout();

						var timeout = setTimeout(function() {
							refreshTorrentsTable();
						},3000);

						$torrents_table.attr('timeout',timeout);
					}
				});

				refreshTorrentsTable();

				$add_torrent_btn.click(function() {
					$add_torrent_modal_url.val('');
					$add_torrent_modal.modal('show');
				});

				$add_torrent_modal.on('show.bs.modal', function(e) {
					$add_torrent_modal_submit.prop('disabled',false);
				});

				$add_torrent_modal.on('shown.bs.modal', function(e) {
					$add_torrent_modal_url.focus();
				});

				$add_torrent_modal_submit.click(function() {
					var url = $add_torrent_modal_url.val();

					if (url) {
						$(this).prop('disabled',true);

						var data = {
							'url': url
						};

						$.ajax({
							url: '{{ url_for("torrent.add") }}',
							type: 'post',
							data: JSON.stringify(data),
							contentType: 'application/json',
	    					dataType: 'json',
	    					beforeSend: function(xhr, settings) {
								if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
									xhr.setRequestHeader("X-CSRFToken", CSRF_TOKEN);
								}
							},
	    					success: function(result,status,xhr) {
	    						var success = result['success'];
	    						if (success) {
	    							notifySuccess('Torrent added');
	    						} else {
	    							notifyError('Fail to add torrent');
	    						}
							},
							complete: function(xhr,status) {
								$add_torrent_modal.modal('hide');
								refreshTorrentsTable(false);
							}
						});
					}
				});

				$delete_torrent_modal.on('show.bs.modal', function(e) {
					$delete_torrent_submit.parent().find('.btn').prop('disabled',false);

					var name = $(this).attr('data-name');
					var uid = $(this).attr('data-uid');

					$delete_torrent_name.text(name);
					$delete_torrent_uid.text(uid);
				});

				$delete_torrent_submit.click(function() {
					var name = $delete_torrent_modal.attr('data-name');
					var uid = $delete_torrent_modal.attr('data-uid');

					if (name && uid) {
						$(this).parent().find('.btn').prop('disabled',true);

						$delete_torrent_modal.removeAttr('data-name');
						$delete_torrent_modal.removeAttr('data-uid');

						var data = {
							'uid': uid
						};

						$.ajax({
							url: '{{ url_for("torrent.delete") }}',
							type: 'post',
							data: JSON.stringify(data),
							contentType: 'application/json',
							dataType: 'json',
							beforeSend: function(xhr, settings) {
								if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
									xhr.setRequestHeader("X-CSRFToken", CSRF_TOKEN);
								}
							},
							success: function(result,status,xhr) {
								var success = result['success'];

								if (success) {
									notifySuccess('Torrent deleted');
								} else {
									notifyError('Fail to delete torrent');
								}
							},
							complete: function(xhr,status) {
								$delete_torrent_modal.modal('hide');
								refreshTorrentsTable(false);
							}
						});
					}
				});
			});
		</script>
	</body>
</html>