app/mod_file/controllers.py
from flask import Blueprint, render_template, jsonify, request, Response
from app.lib import isFolder, isFile, deleteFolder
import os
import json
import gevent
import config

mod_file = Blueprint('file', __name__, url_prefix='/file')

@mod_file.route('/')
def index():
	return render_template('file/file.html')

@mod_file.route('/all')
def all():
	results = []

	with os.scandir(config.DOWNLOAD_FOLDER) as it:
		for entry in it:
			if entry.is_dir():
				name = os.path.join(config.DOWNLOAD_FOLDER,entry.name)
				info_filename = os.path.join(name,'torrent_info.json')
				if isFile(info_filename):
					with open(info_filename,'r') as file:
						info = json.load(file)
						info_hash = info.get('info_hash',None)
						name = info.get('name',None)

						if info_hash and name and 'files' in info:
							results.append({
								'info_hash': info_hash,
								'name': name
							})

	return jsonify(results)

@mod_file.route('/delete', methods=['POST'])
def delete():
	data = request.get_json()
	info_hash = data.get('info_hash',None)

	success = False

	if info_hash:
		folder = os.path.join(config.DOWNLOAD_FOLDER,info_hash)
		info_filename = os.path.join(folder,'torrent_info.json')
		if isFile(info_filename):
			with open(info_filename,'r') as file:
				info = json.load(file)

				if info.get('info_hash',None) == info_hash:
					success = True
					deleteFolder(folder)

	results = {
		'info_hash': info_hash,
		'success': success
	}

	return jsonify(results)

@mod_file.route('/view', defaults={'info_hash': None})
@mod_file.route('/view/<info_hash>')
def view(info_hash):
	files = []

	if info_hash:
		folder = os.path.join(config.DOWNLOAD_FOLDER,info_hash)
		info_filename = os.path.join(folder,'torrent_info.json')
		if isFile(info_filename):
			with open(info_filename,'r') as file:
				info = json.load(file)

				if info.get('info_hash',None) == info_hash:
					files = info.get('files',{})

	results = {
		'info_hash': info_hash,
		'files': files
	}

	return jsonify(results)

@mod_file.route('/download')
def download():
	data = request.args
	info_hash = data.get('info_hash',None)
	path = data.get('path',None)

	response = ('',404)

	if info_hash and path:
		folder = os.path.join(config.DOWNLOAD_FOLDER,info_hash)
		info_filename = os.path.join(folder,'torrent_info.json')
		if isFile(info_filename):
			with open(info_filename,'r') as file:
				info = json.load(file)
				files = info.get('files',{})

				file = files.get(path,None)
				size = file['size']

				if file:
					filename = os.path.join(folder,path)
					if isFile(filename):
						def generate(filename):
							with open(filename,'rb') as file:
								while True:
									data = file.read(1024)
									if not data:
										break

									yield data
									gevent.sleep(0)

						response = Response(generate(filename), mimetype='application/octet-stream')
						response.headers['Content-Disposition'] = 'attachment; filename={}'.format(os.path.basename(filename))
						response.headers['Content-Length'] = size

	return response

app/templates/file/file.html
<!DOCTYPE html>
<html lang="en">
	{% include '_header.html' %}

	<body>
		{% include '_navbar.html' %}

		<div class="container-fluid">
			<br/>

			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<div class="card-header"><i class="far fa-folder-open"></i> Files</div>
						<div class="card-body">
							<div class="table-responsive">
								<table class="table table-bordered table-hover" id="files_table"></table>
							</div>
						</div>
					</div>
				</div>
			</div>

			<br/>
		</div>

		<div class="modal fade" id="delete_file_modal">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title">Delete File</h4>
						<button type="button" class="close" data-dismiss="modal">&times;</button>
					</div>

					<div class="modal-body">
						<div class="col-md-12">
							<p>Are you sure you want to delete "<span id="name"></span>"? (INFO_HASH=<span id="info_hash"></span>)</p>
						</div>
					</div>

					<div class="modal-footer">
						<button type="button" class="btn btn-outline-danger" id="submit">Yes</button>
						<button type="button" class="btn btn-outline-secondary" data-dismiss="modal">No</button>
					</div>
				</div>
			</div>
		</div>

		<div class="modal fade" id="view_file_modal">
			<div class="modal-dialog extralarge-modal">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title"><span id="name"></span></h4>
						<button type="button" class="close" data-dismiss="modal">&times;</button>
					</div>

					<div class="modal-body">
						<div class="col-md-12">
							<div class="table-responsive">
								<table class="table table-bordered table-hover" id="table"></table>
							</div>
						</div>
					</div>

					<div class="modal-footer">
						<button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
					</div>
				</div>
			</div>
		</div>

		{% include '_scripts.html' %}

		{% raw %}
		<script id="name-button-template" type="text/x-handlebars-template">
			<button type="button" class="btn btn-link nopadding" onclick="viewFile('{{name}}','{{info_hash}}')">{{name}}</button>
		</script>
		{% endraw %}

		{% raw %}
		<script id="download-button-template" type="text/x-handlebars-template">
			<a href="{{url}}" target="_blank" class="btn btn-link"><i class="fas fa-download"></i></a>
		</script>
		{% endraw %}

		{% raw %}
		<script id="delete-button-template" type="text/x-handlebars-template">
			<button type="button" class="btn btn-link" onclick="deleteFile('{{name}}','{{info_hash}}')"><i class="far fa-trash-alt color-red"></i></button>
		</script>
		{% endraw %}

		<script>
			var $files_table;
			var $delete_file_modal;
			var $delete_file_name;
			var $delete_file_info_hash;
			var $delete_file_submit;
			var $view_file_modal;
			var $view_file_name;
			var $view_file_table;

			var delete_button_template = Handlebars.compile(document.getElementById('delete-button-template').innerHTML);
			var name_button_template = Handlebars.compile(document.getElementById('name-button-template').innerHTML);
			var download_button_template = Handlebars.compile(document.getElementById('download-button-template').innerHTML);

			function deleteFile(name,info_hash) {
				$delete_file_modal.attr('data-name',name);
				$delete_file_modal.attr('data-info-hash',info_hash);

				$delete_file_modal.modal('show');
			}

			function viewFile(name,info_hash) {
				$view_file_name.text(name);

				$view_file_table.bootstrapTable('destroy');
				$view_file_table.bootstrapTable({
					url: '{{ url_for("file.view") }}/' + info_hash,
					showRefresh: true,
					search: true,
					pagination: true,
					buttonsClass: 'outline-secondary',
					icons: {
						refresh: 'fas fa-sync'
					},
					responseHandler: function(res) {
						var arr = [];

						var files = res['files'];
						for (var key in files) {
							var info = files[key];
							var md5 = info['md5'];
							var size = info['size'];

							var filepath = key.replace(/\\/g,'/');
							var filepathsplit = filepath.split('/');

							var filename = filepathsplit.pop();
							var path = filepathsplit.join('/');

							if (path) {
								path = path + '/';
							} else {
								path = '-';
							}

							var size_col = '<div class="nowordbreak">' + formatBytes(size,1) + '</div>';

							var url = '{{ url_for("file.download") }}?info_hash=' + encodeURIComponent(info_hash) + '&path=' + encodeURIComponent(key);
							var download_col = download_button_template({
								'url': url
							});

							d = {
								'1': path,
								'2': filename,
								'3': size_col,
								'4': download_col,
								'size': size
							}
							
							arr.push(d);
						}
						
						return arr;
					},
					columns: [{
						field: '1',
						title: 'Path',
						sortable: 'true',
						width: '20%'
					}, {
						field: '2',
						title: 'Filename',
						sortable: 'true',
						width: '80%'
					}, {
						field: '3',
						title: 'Size',
						sortable: 'true',
						sortName: 'size'
					}, {
						field: '4',
						title: '<i class="fas fa-download"></i>',
						align: 'center'
					}]
				});

				$view_file_modal.modal('show');
			}

			function resetFilesTableTimeout() {
				var timeout = $files_table.attr('timeout');

				if (timeout) {
					clearTimeout(timeout);
				}
			}

			function refreshFilesTable(silent) {
				resetFilesTableTimeout();

				if (silent === undefined) {
					silent = true;
				}

				$files_table.removeAttr('timeout');
				$files_table.bootstrapTable('refresh',{silent: silent});
			}

			$(document).ready(function() {
				$files_table = $('#files_table');
				$delete_file_modal = $('#delete_file_modal');
				$delete_file_name = $delete_file_modal.find('#name');
				$delete_file_info_hash = $delete_file_modal.find('#info_hash');
				$delete_file_submit = $delete_file_modal.find('#submit');
				$view_file_modal = $('#view_file_modal');
				$view_file_name = $view_file_modal.find('#name');
				$view_file_table = $view_file_modal.find('#table');

				$files_table.bootstrapTable({
					url: '{{ url_for("file.all") }}',
					showRefresh: true,
					search: true,
					pagination: true,
					buttonsClass: 'outline-secondary',
					icons: {
						refresh: 'fas fa-sync'
					},
					responseHandler: function(res) {
						var arr = [];
						
						for (var i = 0; i < res.length; i++) {
							var r = res[i];
							
							var info_hash = r['info_hash'];
							var name = r['name'];

							var name_col = name_button_template({
								'name': name,
								'info_hash': info_hash
							});

							var delete_col = delete_button_template({
								'name': name,
								'info_hash': info_hash
							});

							d = {
								'1': info_hash,
								'2': name_col,
								'3': delete_col,
								'name': name
							}
							
							arr.push(d);
						}
						
						return arr;
					},
					columns: [{
						field: '1',
						title: 'Info Hash',
						sortable: 'true',
						width: '25%'
					}, {
						field: '2',
						title: 'Name',
						sortable: 'true',
						width: '75%',
						sortName: 'name'
					}, {
						field: '3',
						title: '<i class="far fa-trash-alt"></i>',
						align: 'center'
					}],
					onRefresh: function(params) {
						resetFilesTableTimeout();

						var timeout = setTimeout(function() {
							refreshFilesTable();
						},3000);

						$files_table.attr('timeout',timeout);
					}
				});

				refreshFilesTable();

				$delete_file_modal.on('show.bs.modal', function(e) {
					$delete_file_submit.parent().find('.btn').prop('disabled',false);

					var name = $(this).attr('data-name');
					var info_hash = $(this).attr('data-info-hash');

					$delete_file_name.text(name);
					$delete_file_info_hash.text(info_hash);
				});

				$delete_file_submit.click(function() {
					var name = $delete_file_modal.attr('data-name');
					var info_hash = $delete_file_modal.attr('data-info-hash');

					if (name && info_hash) {
						$(this).parent().find('.btn').prop('disabled',true);

						$delete_file_modal.removeAttr('data-name');
						$delete_file_modal.removeAttr('data-info-hash');

						var data = {
							'info_hash': info_hash
						};

						$.ajax({
							url: '{{ url_for("file.delete") }}',
							type: 'post',
							data: JSON.stringify(data),
							contentType: 'application/json',
							dataType: 'json',
							beforeSend: function(xhr, settings) {
								if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
									xhr.setRequestHeader("X-CSRFToken", CSRF_TOKEN);
								}
							},
							success: function(result,status,xhr) {
								var success = result['success'];

								if (success) {
									notifySuccess('File deleted');
								} else {
									notifyError('Fail to delete file');
								}
							},
							complete: function(xhr,status) {
								$delete_file_modal.modal('hide');
								refreshFilesTable(false);
							}
						});
					}
				});
			});
		</script>
	</body>
</html>