app/mod_auth/controllers.py
from flask import Blueprint, request, render_template, redirect, url_for
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash
from app.mod_auth.forms import LoginForm
from app.mod_auth.models import User
from app.lib import getUsers, login_exempt
import app

mod_auth = Blueprint('auth', __name__, url_prefix='/auth')

@mod_auth.route('/login', methods=['GET','POST'])
@login_exempt
def login():
	form = LoginForm(request.form)
	error = None

	if form.validate_on_submit():
		username = request.form.get('username')
		password = request.form.get('password')
		rememberme = request.form.get('rememberme',False)

		users = getUsers()

		password_hash = users.get(username,None)
		if password_hash and check_password_hash(password_hash,password):
			user = User(username)
			login_user(user,remember=rememberme)
			return redirect(url_for('main.index'))
		else:
			error = 'Incorrect username or password'

	return render_template('auth/login.html', form=form, error=error)

@mod_auth.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('auth.login'))

app/mod_file/controllers.py
from flask import Blueprint, render_template, jsonify, request, Response
from app.lib import isFolder, isFile, deleteFolder
import os
import json
import gevent
import config

mod_file = Blueprint('file', __name__, url_prefix='/file')

@mod_file.route('/')
def index():
	return render_template('file/file.html')

@mod_file.route('/all')
def all():
	results = []

	with os.scandir(config.DOWNLOAD_FOLDER) as it:
		for entry in it:
			if entry.is_dir():
				name = os.path.join(config.DOWNLOAD_FOLDER,entry.name)
				info_filename = os.path.join(name,'torrent_info.json')
				if isFile(info_filename):
					with open(info_filename,'r') as file:
						info = json.load(file)
						info_hash = info.get('info_hash',None)
						name = info.get('name',None)

						if info_hash and name and 'files' in info:
							results.append({
								'info_hash': info_hash,
								'name': name
							})

	return jsonify(results)

@mod_file.route('/delete', methods=['POST'])
def delete():
	data = request.get_json()
	info_hash = data.get('info_hash',None)

	success = False

	if info_hash:
		folder = os.path.join(config.DOWNLOAD_FOLDER,info_hash)
		info_filename = os.path.join(folder,'torrent_info.json')
		if isFile(info_filename):
			with open(info_filename,'r') as file:
				info = json.load(file)

				if info.get('info_hash',None) == info_hash:
					success = True
					deleteFolder(folder)

	results = {
		'info_hash': info_hash,
		'success': success
	}

	return jsonify(results)

@mod_file.route('/view', defaults={'info_hash': None})
@mod_file.route('/view/<info_hash>')
def view(info_hash):
	files = []

	if info_hash:
		folder = os.path.join(config.DOWNLOAD_FOLDER,info_hash)
		info_filename = os.path.join(folder,'torrent_info.json')
		if isFile(info_filename):
			with open(info_filename,'r') as file:
				info = json.load(file)

				if info.get('info_hash',None) == info_hash:
					files = info.get('files',{})

	results = {
		'info_hash': info_hash,
		'files': files
	}

	return jsonify(results)

@mod_file.route('/download')
def download():
	data = request.args
	info_hash = data.get('info_hash',None)
	path = data.get('path',None)

	response = ('',404)

	if info_hash and path:
		folder = os.path.join(config.DOWNLOAD_FOLDER,info_hash)
		info_filename = os.path.join(folder,'torrent_info.json')
		if isFile(info_filename):
			with open(info_filename,'r') as file:
				info = json.load(file)
				files = info.get('files',{})

				file = files.get(path,None)
				size = file['size']

				if file:
					filename = os.path.join(folder,path)
					if isFile(filename):
						def generate(filename):
							with open(filename,'rb') as file:
								while True:
									data = file.read(1024)
									if not data:
										break

									yield data
									gevent.sleep(0)

						response = Response(generate(filename), mimetype='application/octet-stream')
						response.headers['Content-Disposition'] = 'attachment; filename={}'.format(os.path.basename(filename))
						response.headers['Content-Length'] = size

	return response

app/templates/_header.html
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

	<link href="{{ url_for('static', filename='css/fontawesome-all.min.css') }}" rel="stylesheet">

	<link href="{{ url_for('static', filename='css/bootstrap-table.min.css') }}" rel="stylesheet">

	<link href="{{ url_for('static', filename='css/animate.css') }}" rel="stylesheet">

	<link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet">

	<title>WebTorz</title>
</head>

app/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar">
	<a class="navbar-brand" href="{{ url_for('main.index') }}">WebTorz</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
		        <a class="nav-link" href="{{ url_for('main.index') }}"><i class="fas fa-cloud-download-alt"></i> Torrents</a>
	      	</li>
	      	<li class="nav-item">
		        <a class="nav-link" href="{{ url_for('file.index') }}"><i class="far fa-folder-open"></i> Files</a>
	      	</li>
		</ul>

		<ul class="navbar-nav">
			<li class="nav-item">
				<span class="d-sm-none"><hr/></span>
		        <a class="nav-link" href="{{ url_for('auth.logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
	      	</li>
		</ul>
	</div>
</nav>

app/templates/_scripts.html
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-table.min.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-notify.min.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/handlebars-v4.0.11.js') }}"></script>

{% raw %}
<script id="notify-template" type="text/x-handlebars-template">
	<div data-notify="container" class="col-11 col-sm-3 alert alert-{0}" role="alert">
		<button type="button" aria-hidden="true" class="close" data-notify="dismiss">×</button>
		<span data-notify="icon"></span> <span data-notify="title">{1}</span> <span data-notify="message">{2}</span>
		<div class="progress" data-notify="progressbar">
			<div class="progress-bar progress-bar-{0}" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"></div>
		</div>
		<a href="{3}" target="{4}" data-notify="url"></a>
	</div>
</script>
{% endraw %}

<script>
	var CSRF_TOKEN = '{{ csrf_token() }}';

	var NOTIFY_TEMPLATE = Handlebars.compile(document.getElementById('notify-template').innerHTML);

	function formatBytes(bytes,decimals) {
		if (bytes == 0) return '0 Bytes';
		var k = 1024,
		dm = decimals || 2,
		sizes = ['Bytes','KB','MB','GB','TB','PB','EB','ZB','YB'],
		i = Math.floor(Math.log(bytes) / Math.log(k));
		return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
	}

	function notify(icon,title,message,type) {
		$.notify({
			icon: icon,
			title: title,
			message: message,
			target: '_blank'
		},{
			element: 'body',
			type: type,
			template: NOTIFY_TEMPLATE()
		});
	}

	function notifyError(message) {
		notify('fas fa-exclamation-triangle','',message,'danger');
	}

	function notifyWarning(message) {
		notify('fas fa-exclamation-circle','',message,'warning');
	}

	function notifySuccess(message) {
		notify('fas fa-check-circle','',message,'success');
	}
</script>

<script>
	$(document).ready(function() {
		var currentPage = window.location.pathname;
		$("#navbar ul li a[href='" + currentPage + "']").parent().addClass("active");
	});
</script>